import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

const faqItems=[
  {question:"Do replacement windows require a permit in Hernando County?",answer:"Hernando County lists garage door and window/door change-outs among residential permits that registered contractors can self-issue through the Contractor Portal."},
  {question:"Does replacing only the glass require a building permit?",answer:"The County's current residential exemption list includes glass replacement in an existing window or door when only the glass is replaced and the frame is not changed."},
  {question:"Do exterior door replacements require a permit in Hernando County?",answer:"Hernando County includes window/door change-outs in its residential self-issuance permit list for registered contractors. Confirm the exact permit requirement for the opening and product before installation."},
  {question:"Who should pull the permit for a window or door replacement?",answer:"The permit responsibility should be stated in the written project scope. A licensed contractor can confirm the required permit and coordinate it when the work falls within the contractor's authorized scope."},
  {question:"Are impact-rated windows automatically required for every replacement?",answer:"Product and opening requirements depend on the applicable code, location and project details. Do not assume every replacement has the same product requirement; verify the approved product and permit requirements for the specific opening."},
];
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqItems.map(x=>({"@type":"Question",name:x.question,acceptedAnswer:{"@type":"Answer",text:x.answer}}))};

export default function Page(){return <main className="blog-page article-page">
  <SiteHeader/>
  <nav className="article-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/faq">FAQs</a><span>/</span><span>Window &amp; Door Permits</span></nav>
  <header className="article-header"><p className="eyebrow">HERNANDO COUNTY • WINDOWS &amp; DOORS FAQ</p><h1>Do I Need a Permit to Replace Windows or Exterior Doors in Hernando County?</h1><p className="article-deck">Window and exterior-door replacement is more than a product swap. The opening, approved product, installation and permit requirements all need to line up.</p><div className="article-meta"><span>WINDOW &amp; DOOR FAQ</span><span>UPDATED SEPTEMBER 28, 2026</span></div><div className="article-byline"><img className="article-author-avatar" src="/assets/william-swift.jpg" alt="William Swift"/><div className="article-author-copy"><span>Author</span><strong>William Swift</strong></div><div className="article-read-time"><span>Read Time</span><strong>6 min read</strong></div></div></header>
  <figure className="article-hero-image"><img src="/assets/windows-doors-hero.png" alt="Replacement window installation in a Florida stucco home"/><figcaption>Hernando County distinguishes window and door change-outs from glass-only replacement.</figcaption></figure>
  <div className="article-shell">
    <aside className="article-sidebar"><div className="article-contents"><p>On This Page</p><a href="#quick">Quick Answer</a><a href="#changeout">Window &amp; Door Change-Outs</a><a href="#glass-only">Glass-Only Replacement</a><a href="#scope">What the Scope Should Cover</a><a href="#before">Before Installation</a><a href="#faqs">FAQs</a></div><div className="article-sidebar-cta"><p>Replacing Openings?</p><h2>Plan the Product and the Installation Together.</h2><a className="button blog-primary" href="/contact">Request a Free Estimate</a></div></aside>
    <article className="article-body">
      <section className="article-answer" id="quick"><p className="eyebrow">QUICK ANSWER</p><h2>Window and Exterior-Door Change-Outs Are Permitted Work in Hernando County.</h2><p>Hernando County currently lists garage door and window/door change-outs among residential permits that registered contractors can self-issue through the Contractor Portal. The County separately lists glass-only replacement in an existing window or door as exempt when the frame is not being replaced.</p><div className="article-takeaways"><strong>Key Takeaways</strong><ul><li>A full window or exterior-door change-out is not the same as replacing glass only.</li><li>Hernando County lists window/door change-outs among residential self-issuance permits for registered contractors.</li><li>Glass-only replacement in an existing frame appears on the County&apos;s residential exemption list.</li><li>The written estimate should say whether permit coordination is included.</li><li>Product selection should be confirmed for the actual opening and applicable requirements.</li></ul></div></section>

      <section id="changeout"><p className="eyebrow">FULL REPLACEMENT</p><h2>Changing the Window or Door Unit Changes the Permit Conversation.</h2><p>When the existing unit and frame are being removed and replaced, Hernando County treats the project differently from simple glass repair. The County&apos;s contractor guidance specifically lists window/door change-outs as a residential permit type available through its contractor portal.</p><p>If you are planning replacement windows or exterior doors, Swift&apos;s <a href="/windows-doors">window and door installation service</a> covers the opening, installation and related finish work as one project scope.</p></section>

      <section id="glass-only"><p className="eyebrow">LIMITED REPAIR</p><h2>Glass-Only Replacement Is Listed Separately.</h2><p>Hernando County&apos;s current residential exemption document includes replacement of existing window and door glass when the project is glass only and the frame is not being changed. That narrow exemption should not be treated as a blanket exemption for replacing the complete unit.</p><p>This distinction matters when comparing bids. One contractor may be quoting a repair while another is quoting full replacement. The price difference can be legitimate because the scope is different.</p></section>

      <section id="scope"><p className="eyebrow">WRITTEN SCOPE</p><h2>Make Sure the Proposal Covers More Than the Product.</h2><p>A useful window or door proposal should identify what is being replaced and what surrounding work is included. Depending on the project, that can include removal, opening preparation, flashing or water-management details, installation, interior trim, stucco, drywall and paint touch-up.</p><ul className="article-checklist"><li>Exact openings included in the project</li><li>Product type and specifications</li><li>Permit responsibility</li><li>Removal and disposal of existing units</li><li>Opening preparation and weather protection</li><li>Interior and exterior finish work</li></ul><p>For related Florida window guidance, read <a href="/blog/25-percent-rule-windows-florida">What Is the 25% Rule for Windows in Florida?</a> and <a href="/blog/energy-efficient-windows-spring-hill">Energy-Efficient Windows in Spring Hill</a>.</p></section>

      <section id="before"><p className="eyebrow">BEFORE INSTALLATION</p><h2>Verify the Opening, Product and Permit Before Work Begins.</h2><p>Do not rely on a general statement that a product is “Florida approved.” The installation still has to match the specific opening, approved product information and applicable local requirements. The contractor should also be able to explain who is handling the permit and inspections when they apply.</p><p>If you are comparing multiple proposals, use the <a href="/blog/compare-remodeling-estimates-spring-hill">remodeling estimate comparison guide</a> to compare scope and contractor responsibility rather than looking only at the total price.</p></section>

      <section className="article-faqs" id="faqs"><p className="eyebrow">COMMON QUESTIONS</p><h2>Hernando County Window &amp; Door Permit FAQs</h2>{faqItems.map((x,i)=><details open={i===0} key={x.question}><summary>{x.question}<span>+</span></summary><p>{x.answer}</p></details>)}</section>
      <section className="article-sources"><p className="eyebrow">OFFICIAL RESOURCES</p><h2>Check the Current County Requirement.</h2><ul><li><a href="https://www.hernandocounty.us/building-development/building/contractors/" target="_blank" rel="noreferrer">Hernando County Contractor &amp; Permit Information</a></li><li><a href="https://www.hernandocounty.us/media/q1oat1te/items-not-requiring-a-building-permit-document.pdf" target="_blank" rel="noreferrer">Hernando County: Items Not Requiring a Building Permit</a></li></ul></section>
    </article>
  </div>
  <section className="blog-cta"><div><p className="eyebrow">PLANNING WINDOW OR DOOR REPLACEMENT?</p><h2>Price the Complete Opening, Not Just the Product.</h2><p>Swift can review the openings, discuss replacement options and prepare a written project scope.</p></div><div><a className="button blog-primary" href="/contact">Request a Free Estimate</a><a href="/faq">More FAQs</a></div></section>
  <SiteFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
</main>}